# Generated by Django 4.1.7 on 2023-04-26 05:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('auto_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
            ],
            options={
                'db_table': 'category',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('auto_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField(max_length=255)),
                ('mrp', models.TextField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
            options={
                'db_table': 'products',
                'ordering': ('category',),
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('auto_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/images')),
                ('is_deleted', models.BooleanField(default=False)),
                ('product', models.ForeignKey(limit_choices_to={'is_deleted': False}, on_delete=django.db.models.deletion.CASCADE, to='app.products')),
            ],
            options={
                'db_table': 'product_image',
                'ordering': ('product',),
            },
        ),
    ]
