# Generated by Django 4.1.7 on 2023-04-26 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_creator_category_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='auto_id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='auto_id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='auto_id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
